feat: add test for keys
team-zomsa/aplib.net-demo pull request #103
Opened 2024-06-19 16:59 UTC by SSelinn

## Description

Added a simple test to check door and key functionality. Also added aplib test.

## Testability

Run test called KeyTests.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-06-19 19:35 UTC, SilasPeters requested changes
To prevent others from needing to rewrite this test later, you should make use of Combinators and lifting. I guess that no other tests use that now, but I will push my commits in my PR so that you can see some examples :)

If you don't get them, I can expain.

2024-06-19 19:35 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Inventory/KeyRing.cs
> +    }
This can be a lambda as well :) But that's a matter of personal preference

2024-06-19 19:35 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/KeyTests.cs
> +        Assert.AreEqual(Color.blue, gameObject.GetComponent<MeshRenderer>().material.color);
This should be moved to a unit tests folder, so not aplib tests or playtests

2024-06-21 12:31 UTC, SilasPeters approved these changes

2024-06-24 11:15 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/AplibTests/KeyTests.cs
> +using Aplib.Core.Desire.DesireSets;
some of these usings are unused

2024-06-24 11:30 UTC, JoenvandeVorle submitted a review, later dismissed
Don't forget to delete the other branch as well

2024-06-24 11:30 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/AplibTests/KeyTests.cs
> +
Please put the test in the testing namespace
```csharp
namespace Testing.AplibTests
{
    public class KeyTests
    {
        ...
    }
}
```

2024-06-24 11:50 UTC, SilasPeters approved these changes

2024-06-25 09:33 UTC, SilasPeters approved these changes

2024-06-25 14:03 UTC, SilasPeters requested changes
Please revert de een na laatse en 2na laatse commits

2024-06-25 18:47 UTC, SilasPeters approved these changes

2024-06-25 19:28 UTC, SilasPeters submitted a review, later dismissed

2024-06-25 19:48 UTC, JensSteenmetz requested changes
Great work! Two small nits for clearer names

2024-06-25 19:48 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Testing/AplibTests/KeyTests.cs
> +            });
```suggestion
            public GameObject Player { get; } = GameObject.Find("Player");
```

2024-06-25 19:48 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Testing/AplibTests/KeyTests.cs
> +                    x => x == null
```suggestion
                    door => door == null
```

2024-06-25 20:14 UTC, JensSteenmetz approved these changes
LGTM!

2024-06-25 20:17 UTC, SilasPeters approved these changes

2024-06-25 20:37 UTC, merged