test: GamePlayTests
team-zomsa/aplib.net-demo pull request #108
Opened 2024-06-23 19:06 UTC by SilasPeters

## Description

The test to test all tests!
What it tests exactly, is expressed in the `GamePlayTests.cs` file.

In the process of making logic work, many gameobjects have been given a new layer.

Furthermore, this fixes a bug where an enemy can spawn in starting room.

> The test is not optimised, some logic has been expressed but is not tested or visible with the current seed of the level, and it is not completely visible when the enemies get killed.
> Furthermore, there is a bug in the game where you hit enemies that are not visible or out of range. Please ignore this, for this is out of scope of the game.
> Also, yes the healing works but that is not visible in the current seed. That's simply because the agent is too smart. I will try to make him get damage somehow.

## Testability

Run the tests.

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-06-23 19:18 UTC, joachimdekker commented on aplib.net-demo/Assets/Materials/Colors/Dark Blue Mat.mat
> +    - _Color: {r: 0.06862936, g: 0.45377082, b: 0.7132075, a: 1}
![image](https://github.com/team-zomsa/aplib.net-demo/assets/51530837/93985d60-8c9b-45f7-ad76-2220bee08d64)

2024-06-23 20:03 UTC, QuakeEye commented on aplib.net-demo/Assets/Materials/Colors/Dark Blue Mat.mat
> +    - _Color: {r: 0.06862936, g: 0.45377082, b: 0.7132075, a: 1}
https://github.com/team-zomsa/aplib.net-demo/assets/74355598/b84ec46c-bb6a-4834-901d-7d6a0d97a66a

2024-06-24 07:21 UTC, JensSteenmetz approved these changes
LGTM!

2024-06-24 11:09 UTC, JoenvandeVorle requested changes
lgtm overall! Got a few comments

2024-06-24 11:09 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/AplibTests/GameplayTests.cs
> +                    ~LayerMask.GetMask("PlayerSelf", "Item", "Ignore Raycast"));
It is not clear to me why you only need those layers. Maybe add a small comment explaining why

2024-06-24 11:23 UTC, JoenvandeVorle approved these changes
awimo!

2024-06-24 11:27 UTC, QuakeEye approved these changes
![image](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/956f528e-203f-4a8e-ab73-eab452dc8f37)

2024-06-24 11:49 UTC, merged