Feat: adds empty room and corridor models
team-zomsa/aplib.net-demo pull request #21
Opened 2024-03-28 11:57 UTC by SSelinn

All models of corridor and empty room are in the prefab folder. The teleport room is scrapped. We can use a DeadEnd room and have a teleport item that we can later spawn where ever we want to have better control over where it is located.

2024-03-28 12:35 UTC, JoenvandeVorle requested changes
Models look nice, only thing is you should add the `Ground` layer to them so the player can actually walk on it

2024-03-28 14:15 UTC, QuakeEye requested changes

2024-03-28 14:15 UTC, QuakeEye commented on aplib.net-demo/Assets/Prefabs/Empty Room.prefab
Please rename this to `EmptyRoom`, spaces in names can break stuff later on.

2024-03-28 14:15 UTC, QuakeEye commented on aplib.net-demo/Assets/Prefabs/Empty Room.prefab.meta
Please rename this to `EmptyRoom`, spaces in names can break stuff later on.

2024-03-28 14:15 UTC, QuakeEye commented on aplib.net-demo/Assets/Prefabs/Corner.prefab
As an overal comment for all prefabs (so handle this for all of them), please add the proper layer so the player can interact with them (in this case, at least for now, layer `Ground`)

2024-03-28 14:15 UTC, QuakeEye commented on aplib.net-demo/Assets/Prefabs/Corner.prefab
As an overal comment for all prefabs (so handle this for all of them), please do not put them in the root of the prefab folder, make some path such as `Assets/Prefabs/Environment/ProBuilderPieces` or something like that

2024-03-28 16:39 UTC, QuakeEye approved these changes

2024-03-29 11:37 UTC, QuakeEye approved these changes

2024-04-01 13:39 UTC, JoenvandeVorle approved these changes
spime (seems perfect in my eyes)

2024-04-01 14:54 UTC, merged