feat: add aplib to Unity
team-zomsa/aplib.net-demo pull request #25
Opened 2024-04-03 11:22 UTC by JensSteenmetz

## Description

*Desribe what you have done in this pull request*

## Testability

*Describe how to test your changes*

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-04-15 21:54 UTC, SilasPeters commented
This is becoming a mega PR. Can this be split up?

2024-04-19 09:19 UTC, joachimdekker commented
> This is becoming a mega PR. Can this be split up?

This looks like a lot, but it is mostly cosmetic files. There are 3 added script files.

2024-04-19 18:36 UTC, SilasPeters requested changes
Looking good! Just nitpicking here. ALtough, could you remove the edit-mode tests as well?

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/MyFirstAplibTest.cs
> +public class MyFirstBeliefSet : BeliefSet
This class should be in the `Testing.AplibTests` namespace

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/MyFirstAplibTest.cs
> +                float playerSpeed = 10f;
This can be a const

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +public class SolveMazeBeliefSet : BeliefSet
Should also be in the `Testing.ApplibTests` namespace

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/MyFirstAplibTest.cs
> +    public Belief<GameObject, GameObject> Player = new(GameObject.Find("Player"), x => x);
These fields, in both tests, can be made readonly

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +
What if an entity is to his right? You are not filtering the hits to the walls. This does match the name of the method, but it does not appear to be what you are trying to test.

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +
Why is this called a hole, and not just 'nothing'? And why can't there be anything on the right in order to have a hole in the front?

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +
Again, the right does not matter when it comes to the front right?
Perhaps this is part of the algorithm of sticking to the wall, but then please explains so.

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +
Please explain that you determine in what room you are, by testing the floor objects' name.

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +    {
Perhaps explain how you plan to solve the maze? Mention sticking to the wall

2024-04-19 18:36 UTC, SilasPeters commented on aplib.net-demo/Assets/Testing/AplibTests/SolveMazeTest.cs
> +
Why the null? I would add `metadata: null'. The metadata is quite annoyting, and I feel tempted to propose to make it optional through an extension method. But that's not for this PR, and not a suggestion - just a rant

2024-04-22 16:41 UTC, closed without merging