feat: add teleporter logic and prefab
team-zomsa/aplib.net-demo pull request #32
Opened 2024-04-12 20:32 UTC by SilasPeters

## Description

This PR introduces functional teleporters.

## Testability

There is a testscene: `TeleportLevel`. This include an example on how to link two portals together.

## Checklist
- [x] Set the proper pull request name
- [ ] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-04-20 23:52 UTC, joachimdekker requested changes
Looks cool. Left a few comments.

2024-04-20 23:52 UTC, joachimdekker commented on aplib.net-demo/Assets/Scenes/MouseLock.unity
The same goes for all other scenes

2024-04-24 10:04 UTC, SilasPeters commented on aplib.net-demo/Assets/Scenes/MouseLock.unity
Well, this did not age well

2024-04-24 11:56 UTC, SSelinn submitted a review, later dismissed
Looking good!

2024-04-24 12:05 UTC, SilasPeters commented
@SSelinn great! I will merge main now, can you approve again afterwards? @joachimdekker you too?

2024-04-24 12:13 UTC, SilasPeters commented
@joachimdekker @SSelinn it should now work properly after merging!

Thank god for `git reset`, or I would have lost  so much time

2024-04-27 11:32 UTC, joachimdekker submitted a review, later dismissed
Did you write an aplib test for this?

2024-04-29 12:05 UTC, SilasPeters commented
> Did you write an aplib test for this?

@joachimdekker I certainly did just now!

2024-04-29 12:28 UTC, JoenvandeVorle requested changes

2024-04-29 12:28 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Prefabs/Player/Player - TeleportLevel.prefab
What exactly did you change about the player that you had to add a new prefab? Or is this to prevent future changes to the player from breaking your scene

2024-04-29 12:28 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scenes/TestScenes/TeleporterTestScene.unity
It would be really nice if you could showcase the navmesh link functionality here, connecting two separate navmeshes with the teleporter to make them one, just as we want to do in the real game.

2024-04-29 12:28 UTC, SilasPeters commented on aplib.net-demo/Assets/Prefabs/Player/Player - TeleportLevel.prefab
Future changes! But also the collision layers

2024-04-29 12:29 UTC, SilasPeters commented on aplib.net-demo/Assets/Scenes/TestScenes/TeleporterTestScene.unity
That could be, but I will safe this for the connected componets conncting part

2024-04-29 12:35 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Teleporter/Teleporter.cs
> +        public float teleportWindUpTime = 2f;
fixed!

2024-04-29 12:35 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
the teleporter must be public, as others might want to read it. I can't figure out how to make it writable for unity editor only.

2024-04-29 12:48 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
You can fix it just like in the teleporter right? Just make them private and add [SerializeField]. Don't forget to add an underscore to the name though! (you forgot it in the other file)

2024-04-29 13:55 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
Then other code can't access it

2024-04-29 14:00 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
And if other classes want to overwrite it, let them. Might be useful, and it won't brake the behaviour code

2024-04-29 14:53 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
Other code seems to not be using it right now though, but if you think it needs to in the future that is fine.

2024-04-29 14:54 UTC, JoenvandeVorle approved these changes
lgtm

2024-04-29 15:58 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
Take a look at GridPlacer and GridPlacerEditor😄.

2024-05-01 11:36 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Teleporter/Teleporter.cs
> +        /// Get global GameObjet references once.
```suggestion
        /// Get global GameObject references once.
```

2024-05-01 11:38 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Teleporter/Teleporter.cs
> +        /// (as the player thus also exits it).
```suggestion
        /// Triggered when the player exits prematurely to cancel the teleport or when the teleport was successful
        /// (as the player thus also exits it).
```

2024-05-01 11:42 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +            acceleration *= rightHandedRotation ? 1f : -1f;
rightHandedRotation could also be a float that is set to 1f or -1f, instead of a bool, so conditionals are not necessary, but that is up to you

2024-05-01 11:42 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        /// (Re)set to initial state
```suggestion
        /// (Re)set to initial state.
```

2024-05-01 11:43 UTC, QuakeEye commented on aplib.net-demo/Assets/Testing/AplibTests/TeleporterTests.cs
This test needs a teardown which unloads the scene so running another test after this one will not get an error later on

2024-05-01 12:05 UTC, SilasPeters commented on aplib.net-demo/Assets/Scripts/Teleporter/TeleporterFX.cs
> +        [Range(0, .04f)] public float acceleration;
I will look into it the next time!

2024-05-01 12:11 UTC, QuakeEye approved these changes
![image](https://i.pinimg.com/originals/a6/37/38/a6373870819f3f07b8a1e07fa6ac9f45.jpg)

2024-05-01 14:36 UTC, JoenvandeVorle approved these changes
lgtm

2024-05-01 14:37 UTC, merged