feat: aplib 96 add wave function collapse
team-zomsa/aplib.net-demo pull request #50
Opened 2024-04-22 15:57 UTC by Tboefijn

## Description

The wave collapse function is responsible for level generation. It needs to:
- Generate a level based on a grid.
  - Make sure the grid is variable (you don’t have to implement the configuration system now, but make it variable in the function)
- Follow the research done by @SSelinn 

## Testability

Open the Wave Function Collapse scene. If you select `Grid` in the hierarchy you can edit some parameters in the Inspector.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-04-23 22:05 UTC, JensSteenmetz requested changes
Awesome work! Left some style comments, but the generation looks amazing!

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public RoomObjects roomObjects;
```suggestion
        [SerializeField]
        private RoomObjects _roomObjects;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public bool useSeed;
```suggestion
        [SerializeField]
        private bool _useSeed;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public int seed;
```suggestion
        [SerializeField]
        private int _seed;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public int gridWidthX = 10;
```suggestion
        [SerializeField]
        private int _gridWidthX = 10;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public int gridWidthZ = 10;
```suggestion
        [SerializeField]
        private int _gridWidthZ = 10;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +        public int amountOfRooms = 5;
```suggestion
        [SerializeField]
        private int _amountOfRooms = 5;
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +            }
```suggestion
            if (amountOfRooms > gridWidthX * gridWidthZ)
                throw new Exception("The amount of rooms is larger than the available places in the grid.");

            if (useSeed) _random = new Random(seed);
```

2024-04-23 22:05 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/WFC/GridPlacer.cs
> +            int noRooms = 0;
```suggestion
            int numberOfRooms = 0;
```

2024-04-24 15:11 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/WFC/Grid.cs
> +        private (int x, int z) IndexToCoordinates(int index)
In de toekomst komt hier wellicht wel een subclass van dus ik laat het voor nu even zo staan.

2024-04-24 16:09 UTC, JensSteenmetz approved these changes

2024-04-24 16:09 UTC, JensSteenmetz commented
I forgor: LGTM

2024-04-24 17:22 UTC, merged