Test/crossbow test
team-zomsa/aplib.net-demo pull request #51
Opened 2024-04-22 18:16 UTC by JoenvandeVorle

## Description

Adds an aplib test for the crossbow weapon

## Testability

Run the tests. At the moment, "run all tests" is broken (and thus the pipeline too). Run the tests individually and they work.

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-05-15 13:28 UTC, Tboefijn requested changes
Looks good! Left some small comments.

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +        public Belief<GameObject, GameObject> Player = new(GameObject.Find("Player"), x => x);
I am missing a summary here.

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +        public Belief<GameObject, bool> IsEnemyInFront = new(
I am missing a summary here.

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +                }
Deze Log is overbodig.
```suggestion
                if (!Physics.Raycast(x.transform.position, x.transform.forward, out RaycastHit hit, 100)) return false;
```

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +    public class RangedWeaponTest
Ik mis 1 of meerdere summaries die uitleggen wat deze test doet.

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +            }
```suggestion
            bool EnemyKilledPredicate(RangeedWeaponTestBeliefSet beliefSet) => beliefSet.IsEnemyDead;
```

2024-05-15 13:28 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/AplibTests/RangedWeaponTest.cs
> +            }
```suggestion
            bool IsEnemyInFrontPredicate(RangeedWeaponTestBeliefSet beliefSet) => beliefSet.IsEnemyInFront;
```

2024-05-20 12:36 UTC, Tboefijn approved these changes
LGTM!

2024-05-22 10:12 UTC, SSelinn approved these changes
Passed the test

2024-05-22 10:34 UTC, merged