feat: add key prefab
team-zomsa/aplib.net-demo pull request #56
Opened 2024-04-29 11:13 UTC by Tboefijn

## Description

Add a model and prefab for the key.

## Testability

Open the scene KeyPrefab and took a look at the key.

## Checklist
- [X] Set the proper pull request name
- [X] Merged main into your branch
- [X] Added a scene to the game for your changes

2024-04-29 11:51 UTC, JoenvandeVorle requested changes

2024-04-29 11:51 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Models.meta
Please move the materials and prefabs to the appropriate folders, I expected the key prefab to be in the prefabs folder.
Also please remove the readme, .psd file, and extra scene

2024-04-29 18:06 UTC, joachimdekker approved these changes
LGTM

2024-04-30 08:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Models/key.obj
Final nitpick: put the models in the Art/Models folder and delete the current one. LGTM otherwise

2024-05-01 08:07 UTC, JoenvandeVorle approved these changes

2024-05-01 08:58 UTC, joachimdekker approved these changes

2024-05-01 08:58 UTC, merged