feat: add Health Component
team-zomsa/aplib.net-demo pull request #58
Opened 2024-04-29 13:25 UTC by JoenvandeVorle

## Description

Added the Health component to the player and AbstractEnemy.
Also moved the Enemy and Player folders inside an Entity folder together with the Health Component (sorry for the 55 files changed -_-).

## Testability

There is a HealthComponent Scene that has a Player and Enemy with the new Health Component.

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-04-29 14:40 UTC, QuakeEye requested changes
![image](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/7028833d-6ecc-45eb-a913-d2c6d00cb0e7)
Something seems to be wrong with the player components

2024-04-29 20:42 UTC, JensSteenmetz requested changes
Great work! I left a few comments

2024-04-29 20:42 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/Health.cs
> +    [SerializeField] private int _maxHealth = 100;
```suggestion
    [SerializeField]
    private int _maxHealth = 100;
```

2024-04-29 20:42 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/Health.cs
> +    public bool IsDead => Health <= 0;
Comments are missing.

2024-04-29 20:42 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/Health.cs
> +        if (Health <= 0)
```suggestion
        if (IsDead)
```

2024-04-30 09:02 UTC, JoenvandeVorle commented
> ![image](https://private-user-images.githubusercontent.com/74355598/326478224-7028833d-6ecc-45eb-a913-d2c6d00cb0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjY1MjIsIm5iZiI6MTcxNDQ2NjIyMiwicGF0aCI6Ii83NDM1NTU5OC8zMjY0NzgyMjQtNzAyODgzM2QtNmVjYy00NWViLWE5MTMtZDJjNmQwMGNiMGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4MzcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MWJiZDNlODY0OTZhNzk5ZjNhNGEwNzIzYjU4MGIwNzdiOWE5OTc3MTY4N2NhOTMwYTExMmJiNzE5YWMzYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsImCllY5dzs0XwE1IIxzWLaWU7yBR-KfUWeqAkRdp0) Something seems to be wrong with the player components

I can not reproduce this behaviour anymore. Can you check again on your end?

2024-04-30 16:46 UTC, QuakeEye approved these changes

2024-04-30 16:46 UTC, QuakeEye approved these changes
![image](https://i.pinimg.com/originals/a6/37/38/a6373870819f3f07b8a1e07fa6ac9f45.jpg)

2024-04-30 17:57 UTC, JensSteenmetz requested changes
Looks great! One tiny problem with an XML summary.

2024-04-30 17:57 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/HealthComponent.cs
> +    /// <param name="amount">The amount </param>
```suggestion
    /// <param name="amount">The amount of health to be subtracted.</param>
```

2024-04-30 17:57 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/HealthComponent.cs
> +        if (amount >= 0)
Nit
```suggestion
        Health -= amount;
        
        if (amount >= 0)
```

2024-05-01 08:28 UTC, QuakeEye approved these changes

2024-05-01 08:28 UTC, merged