feat: add melee monster
team-zomsa/aplib.net-demo pull request #60
Opened 2024-05-02 15:51 UTC by JoenvandeVorle

## Description

Adds the melee enemy prefab. It can attack and kill the player, with a delay between start of the attack and the hit. 
Also includes some basic player logic so that the player can die.

## Testability

Open the MeleeEnemy scene. A blue respawning enemy should be there and start attacking the player. Once either your or the enemies' health reaches zero you respawn. The enemy grows in size when attacking as a visual indicator. 

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-05-04 11:30 UTC, Tboefijn requested changes
LGTM! Left a styling comment.

2024-05-04 11:30 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/HealthComponent.cs
> +    public int MaxHealth {get => _maxHealth;}
```suggestion
    public int MaxHealth { get => _maxHealth; }
```

2024-05-06 08:19 UTC, joachimdekker submitted a review, later dismissed
LGTM!

2024-05-06 08:46 UTC, Tboefijn approved these changes
LGTM!

2024-05-06 08:48 UTC, joachimdekker approved these changes

2024-05-06 09:02 UTC, merged