feat: add health potion
team-zomsa/aplib.net-demo pull request #65
Opened 2024-05-10 15:51 UTC by JoenvandeVorle

## Description

Adds a collectible health potion, that increases player health when used. 
Also made a few changes to the `Inventory` to fix a bug with picking up multiple of the same item.

## Testability

Open the `HealthPotion` scene to pick up the potions and use them. There is no UI element for health yet so you will need to use Debug statements to see your health.
There is also a `HealthPotionTestScene` for an aplib test.

## Checklist
- [ ] Set the proper pull request name
- [ ] Merged main into your branch
- [ ] Added a scene to the game for your changes

2024-05-13 08:58 UTC, Tboefijn requested changes
Looks good. Left a comment and could you quickly try the solution discussed for PickupableComponent?

2024-05-13 08:58 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Items/HealthPotion.cs
> +            _playerHealth.ReduceHealth(-_healAmount);
Dit vind ik een beetje gekke manier om een player extra health te geven. Zou je misschien een method `IncreaseHealth` toe kunnen voegen? Al is het maar een wrapper die dit doet, voor anderen zal dit beter aanvoelen denk.

2024-05-13 11:20 UTC, Tboefijn submitted a review, later dismissed
LGTM!

2024-05-15 08:48 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Inventory/Inventory.cs
> +                _tempItemList[i].uses++;
Well, it's called startUses, so it sounds like the amount of uses you get on the first pickup (that's what I added in the summary for startUses anyway). If it's supposed to be something different, I would give it a different name like `usesAddedPerPickup`. Whatever you think is best

2024-05-15 08:50 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Items/PickupableItem.cs
> +            inventory.PickUpItem(item);
Not an issue introduced in this PR, issue moved to separate ticket.

2024-05-15 10:24 UTC, Tboefijn submitted a review, later dismissed
LGTM!

2024-05-15 10:50 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Inventory/Item.cs
> +    public float usesAddedPerPickup;
I think this should be an integer o.o

2024-05-15 10:51 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Inventory/Item.cs
>      public float uses;
should be an integer

2024-05-15 11:00 UTC, QuakeEye commented on aplib.net-demo/Assets/Scripts/Items/HealthPotion.cs
> +            Debug.Log("current uses: " + uses);
OEI

2024-05-15 11:04 UTC, Tboefijn approved these changes
LGTM!

2024-05-15 11:10 UTC, merged