feat: add and integrate RespawnableComponent
team-zomsa/aplib.net-demo pull request #73
Opened 2024-05-19 13:52 UTC by joachimdekker

## Description

This PR adds the respawnable component and integrates it into the player and enemies.

## Testability

See the RespanableComponent scene.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-05-22 10:17 UTC, Tboefijn requested changes
Left some comments

2024-05-22 10:17 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/Enemy/DummyEnemy.cs
> +    private void OnRespawn(RespawnableComponent respawnableComponent)
In principe gebruik je de variabele niet dus zou ik het hier in veranderen.
```suggestion
    private void OnRespawn(RespawnableComponent _)
```

2024-05-22 10:17 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/Player/PlayerLogic.cs
> +    }
```suggestion
    private void OnSelfRespawn (RespawnableComponent _) _healthComponent.Reset();
```

2024-05-22 10:17 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/Player/PlayerLogic.cs
>          Debug.Log("Player died!");
Hoort niet bij jou code maar dit is een beetje een overbodige Debug.Log
```suggestion
    {
```

2024-05-22 10:17 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/RespawnableComponent.cs
> +using JetBrains.Annotations;
?

2024-05-22 10:17 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Entities/RespawnableComponent.cs
> +        [SerializeField] public Area _spawnArea;
Voor zover ik weet is dit gebruikelijk voor wat we tot nu toe in de code hebben gedaan. Ook staat er een public maar is de variabele _spawnArea, moet dit private zijn?
```suggestion
        [SerializeField] 
        public Area _spawnArea;
```

2024-05-22 10:31 UTC, JoenvandeVorle requested changes

2024-05-22 10:31 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/RespawnableComponent.cs
While it seems like it should work, it doesn't. The player does not respawn in the respawnarea set for it, and always in the same place.

It would also be nice if you could set the spawnAreas for the enemy prefabs

2024-05-22 10:31 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scenes/RespawnableComponent.unity
You should remove the ResetRigidbody script from the player prefab, and delete the script entirely from our project since it shouldn't be used anymore

2024-05-27 16:07 UTC, JoenvandeVorle approved these changes
Apart from the fact that you forgot to assign the respawn zone to the player in your example scene, lgtm

2024-05-27 18:12 UTC, Tboefijn approved these changes
LGTM!

2024-05-27 18:15 UTC, merged