feat: visually link keys and doors
team-zomsa/aplib.net-demo pull request #74
Opened 2024-05-20 15:16 UTC by JoenvandeVorle

## Description

Adds a new material for the keys, adds text to the doors. Both have the same color

## Testability

Go the GridSystem scene and generate a level

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-05-20 17:00 UTC, Tboefijn requested changes

2024-05-21 07:52 UTC, SSelinn submitted a review, later dismissed
Unlocked this approval

2024-05-21 07:52 UTC, SSelinn commented on aplib.net-demo/Assets/Scripts/Doors/Door.cs
Er zijn nu nummers op de deuren die de volgorde geven hoe je ze opend. Ik denk dus dat dit wel ok is gezien als we 2 groenen deuren hebben met de nummers 3 en 8 en 1 groen sleutel dan kan die van 3 open. So for now it's fine imo.

2024-05-22 09:50 UTC, Tboefijn approved these changes
LGTM!

2024-05-22 10:07 UTC, SSelinn approved these changes
Seems connected

2024-05-22 10:08 UTC, merged