Feat: you died screen
team-zomsa/aplib.net-demo pull request #81
Opened 2024-05-27 10:57 UTC by SSelinn

## Description

I added a gameover ui. I also added in the InGameScene a meleeEnemy to kill the player. When the player is killed the gameover scene will show up and you can quit the game.

## Testability

Go into the Settings scene and press play. Then let the enemy kill the player. You will see a gameover ui with a working cursOr.

## Note
Scene changes in InGameScene. No scenes have been added, because almost all changes were in scripts and the prefab.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [] Added a scene to the game for your changes

2024-05-27 12:33 UTC, JoenvandeVorle requested changes
Also remember to check if you can get the scaling to work

2024-05-27 12:33 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/Player/MouseLock.cs
> +            CanvasManager.Instance.UseMouseInSettingsEvent += OnGameSettingsToggled;
I would rename to MenuOpenedEvent after all

2024-05-27 12:33 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/MainMenu/CanvasManager.cs
> +    private HealthComponent _playerHealth;
No need to save this one as a field

2024-05-27 12:33 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/MainMenu/CanvasManager.cs
> +            _playerHealth.Death += OnPlayerDeath;
```suggestion
           HealthComponent _playerHealth = GameObject.FindGameObjectWithTag("Player").GetComponent<HealthComponent>();
            _playerHealth.Death += OnPlayerDeath;
```

2024-05-27 12:33 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/MainMenu/CanvasManager.cs
> +        _isOnGameSettings = false;
Since you use this code more than once(also in start) maybe extract it to a separate method

2024-05-27 13:46 UTC, LuukBerkers approved these changes

2024-05-29 08:56 UTC, joachimdekker commented on aplib.net-demo/Assets/Testing/UnitTests/UnitTests.asmdef
We don't need this anymore, so please remove this.

2024-05-29 08:57 UTC, joachimdekker commented on aplib.net-demo/Assets/Testing/UnitTests/SetAllCanvasesToInactiveTest.cs
These unit tests don't contribute anything. Please remove them.

2024-05-29 09:41 UTC, JoenvandeVorle requested changes

2024-05-29 09:41 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/MainMenu/CanvasManager.cs
> +
remove this empty line

2024-05-29 09:41 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/UnitTests/SetAllCanvasesToInactiveTest.cs.meta
This one can be removed too

2024-05-29 09:41 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/UnitTests/UnitTests.asmdef.meta
and this file

2024-05-29 09:41 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/UnitTests.meta
and this file

2024-05-29 11:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/AplibTests/MyFirstAplibTest.cs
> +    public class MyFirstAplibTestBeliefSet : BeliefSet
Sorry for the confusion, but I just meant please rename it to what it was, not MyFirstAplibTestBeliefSet but MyFirstBeliefSet

2024-05-29 13:12 UTC, JoenvandeVorle approved these changes
lgtm

2024-05-29 13:46 UTC, joachimdekker approved these changes

2024-05-29 13:55 UTC, merged