fix: fix scene switching bug
team-zomsa/aplib.net-demo pull request #82
Opened 2024-05-28 14:42 UTC by JensSteenmetz

## Description
This PR proposes a fix for [issue AP-156](https://zomsa.atlassian.net/browse/AP-156?atlOrigin=eyJpIjoiODk4Njk3OTUzYTcyNGJhMzgwMWQ4ODk0MDU2OTgwYzUiLCJwIjoiaiJ9). When going from game to menu to game, the game broke. You couldn't move the player, interact with the enemies, or move the camera. Now you can.

## Testability
Try switching back and forth between the main menu scene (Settings) and the game scene (InGameSettings) through the pause menu.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes (used the Settings and InGameSettings scenes)

2024-05-28 14:55 UTC, SSelinn submitted a review, later dismissed
IT WORKS! :D

2024-05-28 21:07 UTC, Tboefijn requested changes
Left a nitpick comment

2024-05-28 21:07 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/InputManager.cs
> +        else Instance = this;
```suggestion
        else 
        {
            Instance = this;
        }
```

2024-05-28 21:16 UTC, Tboefijn approved these changes
LGTM!

2024-05-29 08:17 UTC, SSelinn approved these changes
yeye

2024-05-29 08:17 UTC, merged