feat: add equipment system
team-zomsa/aplib.net-demo pull request #83
Opened 2024-05-29 10:34 UTC by joachimdekker

## Description

This PR adds the equipment system as described in AP-98. 

## Testability

Run all tests, and check if the functionality works when pressing a key in the `EquipmentInventory` scene.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes

2024-05-29 16:06 UTC, JoenvandeVorle requested changes

2024-05-29 16:06 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/InputManager.cs
> +        }
Tip I got from Jens: do this in the equipmentinventory class to prevent bloating the inputmanager too much.

2024-06-03 15:32 UTC, JoenvandeVorle requested changes
Looks good, few more comments

2024-06-03 15:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/Weapons/RangedWeapon.cs
> +                Debug.LogError("AmmoPouch not found in the scene. Defaulting to parent ammo pouch.");
```suggestion
                Debug.LogError("AmmoPouch not assigned. Defaulting to parent ammo pouch.");
```

2024-06-03 15:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +    [SerializeField] private int inventorySize = 2;
```suggestion
    [SerializeField] private int _inventorySize = 2;
```

2024-06-03 15:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +    [SerializeField] public bool SwitchToNewItem;
Public fields are already serialized by default
```suggestion
    public bool SwitchToNewItem;
```

2024-06-03 15:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/PlaymodeTests/RangedEnemyTest.cs
> +public class RangedEnemyTest
Tests look good, but I'm a bit confused why this is called RangedEnemyTest. We're testing the ranged weapon (more specifically the ammo pouch) here right?

2024-06-05 08:23 UTC, Tboefijn requested changes
Looks good! Left some comments.

2024-06-05 08:23 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +                "Default equipment is empty! Rolling back to obsolete implementation. \n "
```suggestion
                "Default equipment is empty! Rolling back to obsolete implementation.\n"
```

2024-06-05 08:23 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +    private int _inventorySize = 2;
Ik zou hier _equipmentInventorySize van maken of iets dergelijks.

2024-06-05 08:23 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Inventory/IEquipment.cs
Hier wordt een abstract class gedefinieerd terwijl de file name suggereert dat hier een interface wordt gedefinieerd.

2024-06-05 08:23 UTC, Tboefijn commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +    public void EquipItem(Weapon equipment)
```suggestion
    public void EquipItem(Equipment equipment)
```
Zou dit ook niet Equipment moeten zijn of kom je dan verkeerd uit met types?

2024-06-05 08:23 UTC, Tboefijn commented on aplib.net-demo/Assets/Testing/PlaymodeTests/RangedWeaponTest.cs
Ik zeg niet perse dat het moet maar om even overnagedacht te hebben. Willen we meerdere testen in 1 file/class hebben of willen we dit gesplitst hebben in verschillende bestanden?

2024-06-05 08:32 UTC, JoenvandeVorle requested changes

2024-06-05 08:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +using UnityEngine.Serialization;
deze import is niet gebruikt

2024-06-05 08:32 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Testing/PlaymodeTests/RangedWeaponTest.cs
> +using Entities.Weapons;
also unused

2024-06-05 09:05 UTC, joachimdekker commented on aplib.net-demo/Assets/Testing/PlaymodeTests/RangedWeaponTest.cs
Opzich hebben beide testen betrekking op de RangedWeapon, dus dan is het logical dat we het opnemen in dezelfde bestanden.

2024-06-05 10:10 UTC, Tboefijn approved these changes
LGTM!

2024-06-05 10:58 UTC, JoenvandeVorle approved these changes
awimo!

2024-06-05 13:27 UTC, Tboefijn approved these changes
LGTM!

2024-06-05 13:50 UTC, JoenvandeVorle approved these changes
lgtm

2024-06-05 13:50 UTC, merged