feat!: add level generation pipeline
team-zomsa/aplib.net-demo pull request #97
Opened 2024-06-12 13:16 UTC by Tboefijn

## Description

This PR puts the Level Generation in a pipeline class. This way it is easier to configure the level and is there less coupling between the classes.

## Testability

Open the scene `LevelGeneration`. Everything should still work as intended.

## Checklist
- [X] Set the proper pull request name
- [X] Merged main into your branch
- [X] Added a scene to the game for your changes

2024-06-12 14:05 UTC, JensSteenmetz requested changes
Aweeeesome work! I feel bad for the nitpick, but... skill issue

2024-06-12 14:47 UTC, JensSteenmetz submitted a review, later dismissed
LGTMMMM

2024-06-12 16:28 UTC, JoenvandeVorle requested changes
nice! got a few comments

2024-06-12 16:28 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scenes/Settings.unity
Pressing play in this scene doesn't seem to work for me

2024-06-12 21:06 UTC, Tboefijn commented on aplib.net-demo/Assets/Scenes/GridSystem.unity
It is outdated and I have deleted it now.

2024-06-13 08:15 UTC, JensSteenmetz approved these changes
LGTM!

2024-06-13 10:19 UTC, JoenvandeVorle approved these changes
lgtm, don't forget to delete your second branch as well

2024-06-13 10:19 UTC, merged