refactor: refactor managers
team-zomsa/aplib.net-demo pull request #99
Opened 2024-06-16 21:19 UTC by JensSteenmetz

## Description
This PR aims to refactor all manager classes. There were two main focuses:
- Manager classes should be referenced by components, not the other way around. This is accomplished through the use of C# events.
- Manager classes shouldn't have to be put in the scene by the user. The singleton pattern should handle the creation of a manager class when a manager is needed. This helps to enforce that managers don't depend on scene objects.

In addition, this PR addresses some of the issues with Cinemachine and the Input System.
- `CinemachinePOVExtensions` has been removed completely.
- Cinemachine is now driven directly by the Input System.

### What prefabs and Scenes have been edited and why/how?
The following prefabs have been edited:
- **Player (modified)**. Added a few scripts for interaction with Cinemachine+Input System.
- **CanvasManager (removed)**. Split into two:
    - GameCanvas (created)
    - MainMenuCanvas (created)
- **FirstPersonCamera (created)**. This prefab makes use of the Input System to look around, and follows the player position. This is for correct camera behavior in the actual game.
- **FollowTargetCamera (created)**. This prefab automatically follows the Player object, for correct camera behavior during aplib tests.

All test scenes, as well as the scenes `Settings`, `InGameSettings`, and `LevelGeneration`, have been updated to be compatible with the new manager classes and Input System. This involves:
- The removal of all manager class objects from these scenes (because they are created automatically by the singleton pattern).
- The use of the new/edited prefabs.

## Testability
1. Check (with visuals, in the editor) if the tests still work correctly.
2. Check if the game still functions as expected (in the scenes `Settings`, `InGameSettings`, and `LevelGeneration`).

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] Added a scene to the game for your changes (N/A)

2024-06-17 11:47 UTC, JoenvandeVorle requested changes
Very nice!! left a few comments

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/Player/MouseLock.cs
The mouse locking does not seem to work anymore, at least not when you press leftalt

Also, when pressing escape to close the menu while in-game, the cursor stays visible

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/Player/MouseLock.cs
> -    public void OnShowMousePressed() => EnableMouseCursor();
This line should probably be brought back and linked to the inputmanager

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/RespawnWhenButtonPressed.cs
> +using System.Collections.Generic;
unused

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/MainMenu/MainMenuCanvas.cs
> +using System.Collections.Generic;
unused

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Misc/GameOverOnDeath.cs
> +using System.Collections.Generic;
unused

2024-06-17 11:47 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Misc/InputManager.cs
> +    public event Action MouseShown;
This is the left alt show mouse press

2024-06-17 13:29 UTC, JensSteenmetz commented on aplib.net-demo/Assets/Scripts/Entities/Player/MouseLock.cs
The second comment: the cursor stays visible because focus is lost in the editor. In the build, this works correctly.

2024-06-18 08:01 UTC, JoenvandeVorle commented
Please excuse my oopsy, I set the branch to its last commit again

2024-06-18 08:29 UTC, JoenvandeVorle requested changes
one thing still missing, otherwise lgtm

2024-06-18 08:29 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Entities/Player/MouseLock.cs
I'm not sure what broke this, but on showing the mouse the camera input was also frozen (like the game was paused). Maybe you can re-add this functionality by calling GameManager.Pause in the EnableCursor method?

2024-06-18 11:53 UTC, SSelinn commented on aplib.net-demo/Assets/Scripts/Util/CopyLocalTransform.cs
> +public class CopyLocalTransform : MonoBehaviour
Doesn't this need a comment?

2024-06-18 11:53 UTC, SSelinn commented on aplib.net-demo/Assets/Scripts/Misc/Singleton.cs
> +public abstract class Singleton<T> : MonoBehaviour
Doesn't this need a comment?

2024-06-18 12:09 UTC, JoenvandeVorle commented on aplib.net-demo/Assets/Scripts/Inventory/EquipmentInventory.cs
> +        if (HasItems) CurrentEquipment.UseEquipment();
You will still need to get the animator from somewhere, but this should do it
```suggestion
        if (HasItems) 
        {
            if (CurrentEquipment is Weapon weapon && weapon.CanFire())
                _playerAnimator.SetTrigger("PlayerAttack");

            CurrentEquipment.UseEquipment();
        }
```

2024-06-18 12:10 UTC, SSelinn approved these changes
Nice

2024-06-18 12:42 UTC, SSelinn approved these changes
Looking good!

2024-06-18 13:20 UTC, JoenvandeVorle submitted a review, later dismissed
awimo! nice job adding comments too

2024-06-18 17:38 UTC, SSelinn approved these changes
Noice

2024-06-19 07:20 UTC, JoenvandeVorle approved these changes
👍

2024-06-19 07:21 UTC, merged